test: update size golden after hello-world-lazy fell below threshold
It was already close to the boundary and the recent image directive
core/common changes caused it to finally exceed the boundaries in
a positive way (i.e. reduction):

Before:

Skipped uploading data for 'cli-hello-world-lazy', because this is a pull request.
Verifying sizes against '/usr/local/google/home/pgschwendtner/.cache/bazel/_bazel_pgschwendtner/84e2b91096f108a3ead3e72250add8ed/execroot/angular/bazel-out/k8-fastbuild/bin/integration/cli-hello-world-lazy/test.sh.runfiles/angular/goldens/size-tracking/integration-payloads.json'...
SUCCESS: Commit undefined uncompressed runtime did NOT cross size threshold of 500 bytes or >1% (expected: 2835, actual: 2825).
SUCCESS: Commit undefined uncompressed main did NOT cross size threshold of 500 bytes or >1% (expected: 230780, actual: 230313).
SUCCESS: Commit undefined uncompressed polyfills did NOT cross size threshold of 500 bytes or >1% (expected: 37244, actual: 37383).
SUCCESS: Commit undefined uncompressed src_app_lazy_lazy_module_ts did NOT cross size threshold of 500 bytes or >1% (expected: 795, actual: 796).

After:

Skipped uploading data for 'cli-hello-world-lazy', because this is a pull request.
Verifying sizes against '/usr/local/google/home/pgschwendtner/.cache/bazel/_bazel_pgschwendtner/84e2b91096f108a3ead3e72250add8ed/execroot/angular/bazel-out/k8-fastbuild/bin/integration/cli-hello-world-lazy/test.sh.runfiles/angular/goldens/size-tracking/integration-payloads.json'...
SUCCESS: Commit undefined uncompressed runtime did NOT cross size threshold of 500 bytes or >1% (expected: 2835, actual: 2825).
SUCCESS: Commit undefined uncompressed polyfills did NOT cross size threshold of 500 bytes or >1% (expected: 37244, actual: 37383).
SUCCESS: Commit undefined uncompressed src_app_lazy_lazy_module_ts did NOT cross size threshold of 500 bytes or >1% (expected: 795, actual: 796).
FAIL: Commit undefined uncompressed main fell below expected size by 500 bytes or >1% (expected: 230780, actual: 230259).
If this is a desired change, please update the size limits in file '../../.cache/bazel/_bazel_pgschwendtner/84e2b91096f108a3ead3e72250add8ed/execroot/angular/bazel-out/k8-fastbuild/bin/integration/cli-hello-world-lazy/test.sh.runfiles/angular/goldens/size-tracking/integration-payloads.json'.
Error: Integration test command: `/usr/local/google/home/pgschwendtner/.cache/bazel/_bazel_pgschwendtner/84e2b91096f108a3ead3e72250add8ed/execroot/angular/bazel-out/k8-fastbuild/bin/integration/cli-hello-world-lazy/test.sh.runfiles/angular/scripts/ci/bazel-payload-size.sh cli-hello-world-lazy 'dist/*.js' true /usr/local/google/home/pgschwendtner/.cache/bazel/_bazel_pgschwendtner/84e2b91096f108a3ead3e72250add8ed/execroot/angular/bazel-out/k8-fastbuil